portal_base_url: "https://zeus41.cyf-kr.edu.pl:8443/aruliferay/api/external/"
portal_shared_key: <%= ENV['portal_shared_key'] %>
portal_test_user: <%= ENV['portal_test_user'] %>
portal_test_password: <%= ENV['portal_test_password'] %>